---
title: "Self Info"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: cerulean
---

# Basic Information

My name is Haotian Tang (Synco). I graduated from the University of Toronto and am currently pursuing the degree of master of science in biostatistics. The specific track is statistical genetics. I am very interested in how we can use mathematical modeling and statistical analyis to dissect genetics. 

# Academic and Professional Experiences

- Investigating How CYP450- and sEH-associated Pathways Play a Role in Alzheimer’s Disease

- Investigating the Mechanism of Antibiotics in vivo and the Development of SARS-COV-2 Vaccines

- Investigating the Interaction of Different Species of Duckweeds and Microbiome

- Investigating the Hypertensive and Psychoactive Effect of Caffeine and the Biochemical Mechanism

- Investigating Factors Affecting "the Marshmallow Experiment" and Delayed Gratification

- Investigating Biodiversity in Forest by Studying the Quantity and Categories of Terrestrial Snails in Tioman Island

More details can be seen in the [Resume](Resume.pdf).

# Hobbies and Interests

I like workout, playing my guitar, listening to music, traveling, and tasting delicious food! 




